name: youtube-playlist-downloader
region: nyc
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: brahianf1/youtube-playlist-downloader
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
  name: youtube-dl-web
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8000"
  - key: DEBUG
    value: "False"